LineLength:
  Enabled: true
  Max: 128

Encoding:
  Enabled: false

CaseIndentation:
  Enabled: false

# MethodLength is superseded by Reek's TooManyStatements smell-finder.
MethodLength:
  Enabled: false
